[package]
name = "logwise"
version = "0.1.1"
authors = ["Drew Crawford <drew@sealedabstract.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "an opinionated logging library for Rust"
homepage = "https://sealedabstract.com/code/logwise"
repository = "https://github.com/drewcrawford/logwise"
keywords = ["logging"]
categories = ["development-tools::debugging", "development-tools::profiling"]

exclude = [".*"]

[dependencies]
logwise_proc = { path = "logwise_proc", version = "0.1.0" }

[dev-dependencies]
